### ISSUE TITLE
aws-okta not able to add

### ISSUE THREAD

**Issue by unrelatedinfo** [segmentio/aws-okta#160]
Hi,
I've come across a weird one, so far it reproduces every time with file or keyring backends.

So far I've not been able to move on and get this working.
It's a fresh install of manjaro with fresh go environment.

Any pointers will be greatly appreciated.

OS info:
```
Linux mimir 4.19.45-1-MANJARO #1 SMP PREEMPT Wed May 22 17:16:41 UTC 2019 x86_64 GNU/Linux
location: /usr/local/bin/aws-okta
go version go1.12.5 linux/amd64
```
**Debug output:**
```
aws-okta -d --backend file add
Okta organization: REDACTED

Okta region ([us], emea, preview): 

Okta domain [REDACTED]: 

Okta username: REDACTED

Okta password: 

DEBU[0013] domain: REDACTED                
DEBU[0013] Step: 1                                      
DEBU[0014] Step: 2                                      
INFO[0014] Requesting MFA. Please complete two-factor authentication with your second device 
DEBU[0014] 00TsQ6q0ybBSC_REDACTED   
DEBU[0014] Okta Factor Provider: OKTA                   
DEBU[0014] Okta Factor ID: REDACTED         
DEBU[0014] Okta Factor Type: sms                        
DEBU[0014] SMS MFA                                      
DEBU[0014] Requesting SMS Code                          
Enter MFA Code from SMS:REDACTED

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x672566]

goroutine 1 [running]:
github.com/segmentio/aws-okta/vendor/github.com/99designs/keyring.(*fileKeyring).resolveDir(0xc000231320, 0xc000376050, 0xc000320140, 0x128, 0x140)
        /home/REDACTED/go/src/github.com/segmentio/aws-okta/vendor/github.com/99designs/keyring/file.go:51 +0x316
github.com/segmentio/aws-okta/vendor/github.com/99designs/keyring.(*fileKeyring).Set(0xc000231320, 0x9eee7b, 0xa, 0xc000252180, 0x71, 0x80, 0x9f2a36, 0x10, 0x0, 0x0, ...)
        /home/REDACTED/go/src/github.com/segmentio/aws-okta/vendor/github.com/99designs/keyring/file.go:109 +0xd5
github.com/segmentio/aws-okta/cmd.add(0xe83a60, 0xc0002312c0, 0x0, 0x3, 0x0, 0x0)
        /home/REDACTED/go/src/github.com/segmentio/aws-okta/cmd/add.go:129 +0x4e9
github.com/segmentio/aws-okta/vendor/github.com/spf13/cobra.(*Command).execute(0xe83a60, 0xc000231200, 0x3, 0x3, 0xe83a60, 0xc000231200)
        /home/REDACTED/go/src/github.com/segmentio/aws-okta/vendor/github.com/spf13/cobra/command.go:647 +0x3ef
github.com/segmentio/aws-okta/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xe83ea0, 0x7, 0x14, 0x33)
        /home/REDACTED/go/src/github.com/segmentio/aws-okta/vendor/github.com/spf13/cobra/command.go:726 +0x2be
github.com/segmentio/aws-okta/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /home/REDACTED/go/src/github.com/segmentio/aws-okta/vendor/github.com/spf13/cobra/command.go:685
github.com/segmentio/aws-okta/cmd.Execute(0x9e9822, 0x3, 0x0, 0x0)
        /home/REDACTED/go/src/github.com/segmentio/aws-okta/cmd/root.go:57 +0x92
main.main()
        /home/REDACTED/go/src/github.com/segmentio/aws-okta/main.go:15 +0x51
```

**Comment by unrelatedinfo** [comment]
Resolved by 
```
export AWS_OKTA_BACKEND=secret-service
```
